### ISSUE TITLE
Provider has no use for BearerAuthorizationTrait

### ISSUE THREAD

**Issue by shadowhand** [Schoolrunner/oauth2-clever#2]
The [`BearerAuthorizationTrait`](https://github.com/Schoolrunner/oauth2-clever/blob/8ef5228b172085a04f9c52a3364f270602ff6d98/src/Provider/Clever.php#L15) is meant to be used to provide `Bearer` token headers for auth. Since Clever has it's own [auth method](https://github.com/Schoolrunner/oauth2-clever/blob/8ef5228b172085a04f9c52a3364f270602ff6d98/src/Provider/Clever.php#L68-L72) there is no reason to include it in the default provider.

Also, `getDefaultHeaders` is the wrong place to put authorization. The correct thing to do would be to define a `getAuthorizationHeaders` method, like the [`BearerAuthorizationTrait` does in oauth2-client](https://github.com/thephpleague/oauth2-client/blob/cea255753d9ce486c425d8126fd0e469496d25db/src/Tool/BearerAuthorizationTrait.php#L30-L33).

**Comment by smoakey** [comment]
Looking through the Abstract provider class. the flow looks to be the following:

1. getAccessToken()
2. getAccessTokenRequest()
3. getRequest()
4. createRequest()
5. getHeaders()

Since getRequest() always calls createRequest() with a NULL $token, which is passed to getHeaders(), then it never calls getAuthorizationHeaders() it only calls getDefaultHeaders()

Am I missing something?

FYI. Clever requires you to pass a base64 encoded version of the client_id & client_secret for the /oauth/tokens endpoint as a Basic Auth Header, but then uses Bearer Auth headers for other endpoints.

**Comment by shadowhand** [comment]
[`getHeaders` makes a call to `getAuthorizationHeaders`](https://github.com/thephpleague/oauth2-client/blob/f145fded7d61a5388e76ed720c5dce185c1d36fe/src/Provider/AbstractProvider.php#L836-L837).

> FYI. Clever requires you to pass a base64 encoded version of the client_id & client_secret for the /oauth/tokens endpoint as a Basic Auth Header, but then uses Bearer Auth headers for other endpoints.

I think this was the key part that I was missing, as the current implementation only allows for it be side effect when no token is present. The more correct implementation would be to overload [`getAccessTokenOptions`](https://github.com/thephpleague/oauth2-client/blob/f145fded7d61a5388e76ed720c5dce185c1d36fe/src/Provider/AbstractProvider.php#L514-L523):

```php
$options = parent::getAccessTokenOptions(array $params);
$options['headers']['authorization'] = 'Basic base64-auth-string';

return $options;
```

This would ensure that the base64 header is _only_ used for fetching the token is not incorrectly attached to any other request.

**Comment by smoakey** [comment]
Ah that makes sense now. Thanks for your help!
